name: maim
version: '3.3.41'
summary: 'A utility that takes screenshots of your desktop using imlib2'
description: |
  maim (Make Image) is a utility that takes screenshots of your desktop using
  imlib2. It's meant to overcome shortcomings of scrot and performs better in
  several ways.
confinement: strict
grade: devel

apps:
  maim:
    command: maim
    plugs: [x11]

parts:
  maim:
    plugin: cmake
    source: https://github.com/naelstrof/maim/archive/v3.3.41.tar.gz
