name: slop
version: '4.2.18'
summary: 'Queries for a selection from the user and prints the region to stdout.'
description: |
  slop (Select Operation) is an application that queries for a selection from
  the user and prints the region to stdout. It grabs the mouse and turns it
  into a crosshair, lets the user click and drag to make a selection (or click
  on a window) while drawing a pretty box around it, then finally prints the
  selection's dimensions to stdout.
confinement: strict
grade: devel

apps:
  slop:
    command: slop
    plugs: [x11]

parts:
  slop:
    plugin: cmake
    source: https://github.com/naelstrof/slop/archive/v4.2.18.tar.gz
